contracts:
  bettingContract: '0xBBd51B391d4895b542D616E32d15EBFe5ef3DDED'
  gameLogic: '0x990AD1284c1270eaa32833802a46169fD8dA35C0'
  handEvaluator: '0x9Ea60FDb07796570F72d2F6F01EA2e3A3109c6Da'
  handManager: '0xb683F73E6f5FC2326083cd113E15B8609F9C758F'
  router: '0x856a55Ad34018d014331645C8e59ACe69bCF3dfC'
  stateStorage: '0x25a15eB7cB507987b669f455D56BFC54622AD986'
  tournamentLogic: '0xF5475aC918e431eA3c793796B0Ac99A3B126B9B4'
