contracts:
  bettingContract: '0x036785ceEBe81B78AB10a3Ba97B1CDDFdFd5f68A'
  gameLogic: '0xe40232c45a0860A9D37045B96799eC371deB5414'
  handEvaluator: '0x2D38ba80cA1d845850b1e28b070441D7A40F33b4'
  handManager: '0x62810D421876982d05938b0D87368f2d23127d89'
  router: '0xD0cB19684111B7629EB87fCb525B12DAD536F0F6'
  stateStorage: '0xe2E974a60c48D706E03ef97353f9e5Ce6Ac7b5Ca'
  tournamentLogic: '0xBf065517ee4Dc7FF08fAf18f0154FcC570a7a2AC'
