contracts:
  bettingContract: '0x680A58db9518706B08F76C997E6988aE4DcE2532'
  gameLogic: '0x28D12A5C269a0B302725657D621353b6ebbaA751'
  handEvaluator: '0xFB419DDF639667855D68A88bdB49153588a95B31'
  handManager: '0x0BeeDd82fD5931b089F7E7D5B2648b02131Bd58F'
  router: '0x6C291B5e8AF5cbb0A5DE6bcEec5245b16AE2a85d'
  stateStorage: '0xc03C30d17aA645EbAD3A3A7B70235dE7ac85064E'
  tournamentLogic: '0x37df04F23e234902bAfC1Fadb6f6b36Ca47da516'
