contracts:
  bettingContract: '0x7aE12941f60aC77fe1a02CB8a54cf0F64d6B00ca'
  gameLogic: '0xAE8D6C738544072e11532D45b30b18Bb43907210'
  handEvaluator: '0xb89983e17229A793a771CFe9f8814Bc87631f89a'
  handManager: '0x47f8B0c4a9e36f010DA5c3721F64c8Fd26287aa0'
  router: '0xCf32B697ee7dF84142F91Ef666f886f6B1863EFA'
  stateStorage: '0xb2415033d4079F55B01aa78c75284296Eea4E518'
  tournamentLogic: '0xFd5AA2AC69a02092055BF2bF06DFc6f3A226EaF3'
