contracts:
  bettingContract: '0x4b9184C1DFA10D4C6AcDEBEE4C712A7210D1fCe9'
  gameLogic: '0x8D1f73e60F8Ca325108A71E0D58F9510ff0eCb94'
  handEvaluator: '0xd8087871e5F248aDE805e1eA608344A9d0EF5a2b'
  handManager: '0xa5A6a53B7f941C0FAc22d1Ec57D727dF26b0806E'
  router: '0xB5697098308c86912d5145E242F287899BdDc3c2'
  stateStorage: '0x1915EB1674797EcfaA989C808743d22A9f775e11'
  tournamentLogic: '0xFcc66717cd6187a545d8707a82ef9A3578d58019'
