contracts:
  bettingContract: '0xa36011EA3B2DD6757454A5861113754D33E4a4DF'
  gameLogic: '0x6A6478cd95308C015Df18228c51A3868122852d6'
  handEvaluator: '0x5b88B9babba3688077826E15a948eaecA31c0b6e'
  handManager: '0x4D32d934531D73a5bdF78f96323D8b010f0F2622'
  router: '0xE216e1f2838081003046613FfCaFEd8C2b4745A9'
  stateStorage: '0xEFb45674B699b346631c06Fa22E7BF1A77b814c6'
  tournamentLogic: '0x8708F06809971077E66384c4A1Ab02546FD7cFea'
