contracts:
  bettingContract: '0x5bDC42dC304Df67896124D4EEDEA4f5478EDC94b'
  gameLogic: '0x5cbbDD404f254d6A6686abd2C4601d1Fce51f839'
  handEvaluator: '0x45D044D505DFEbEf8D2D33395ae5309190494b58'
  handManager: '0x877F7db8E29D65b05a5d5b230E2541d8E2Fa5F9a'
  router: '0xd07Ec822fe68Ef37555b0C1A4052964a24f47d2d'
  stateStorage: '0x09C86f77302a60A578557B697f5dfd60324CC6AA'
  tournamentLogic: '0xE8822d565fA85Ee2af076986266cE157f52d3a7b'
