contracts:
  bettingContract: '0x75495d7DE09a3B9Bd3e8c0ac64180e60fA5BAD97'
  gameLogic: '0x04b8c5bD2554D34398A842cdbE134cb8b135293B'
  handEvaluator: '0x3299ae2bB00Bc1F1852bDa11AF2DEF58C9100166'
  handManager: '0xD1A47D0d4555Dbd2936602d619d5784B860A5628'
  router: '0x71EED32F71a93114E7f9061AdA97439F43434ca3'
  stateStorage: '0x27a49252F602e7Fae987174B8a78D128DDdaE846'
  tournamentLogic: '0xf7160485719306EC72B6e991EEE7369c17C719b8'
