contracts:
  bettingContract: '0x2C81194D4a271c82e900239e092faF20A0817162'
  gameLogic: '0xDb4F7e719284C73F5408E10F2d660DF909b2d310'
  handEvaluator: '0x1e9Bab8D20A842e428c533A0b064A7F142547812'
  handManager: '0xB624893372627fc1295e7a177da22e50d2cB2B95'
  router: '0x0D85222642632fD1d7AcD6160f7fF3f13Ce0AC5A'
  stateStorage: '0xE3dCC5E8E02D46A174Ae64D1C9817447eF196Dcd'
  tournamentLogic: '0xCA2432e369bf1BD575394B439D6Dd7944D1e3EeC'
