contracts:
  bettingContract: '0x302e42BFdA8fd84Fc58Ee18cf0272e326546FacA'
  gameLogic: '0x6d8737CFD40A3ce83ae2DC0197f648a2ba5D4cb6'
  handEvaluator: '0xD09c156dbB40266FfFa68CA69188ae0eF3bAEAe1'
  handManager: '0xF22Eb88A54B65741034d75f712B9B3cf985319a3'
  router: '0x0cb93019c338ebC9C65A14477318DdC68C417C89'
  stateStorage: '0xba485C6D3b6AB13BAe0d56277645b58642caa9f3'
  tournamentLogic: '0xfDfdc23A381c23AA74C654E88d77E6e1983c6D8b'
