contracts:
  bettingContract: '0x589aeB4b38AB3c727079B0E97DeDa5823cD918D2'
  gameLogic: '0xc00baebF146b6d4163E08a3111bCAE8271dCE57D'
  handEvaluator: '0x8C44b32408cD67820C0F7C9A4bFAaB185fcDe386'
  handManager: '0x30beC59470a3b3F487255BF9Dd09f284D278af6A'
  router: '0xfe0170BF3602cD81ab2ade3d51C299a9699f2F68'
  stateStorage: '0x809c97C8973c9A84c3598aa98847e66914F86bBD'
  tournamentLogic: '0x446015cc2560d6d6ad05E407503ad21caa2288Fe'
