contracts:
  bettingContract: '0xb7F8bB875Bb8A3F788c8688ba9175637673d2bdF'
  gameLogic: '0x5806ee8F3C6472c3BB1c9264FF6ee2b48bA71C0f'
  handEvaluator: '0xf07242702f03836B3279f5f0e46C8dF3ed6dA809'
  handManager: '0x1105c92734EF2587105A4537EDE88f678E8B4249'
  router: '0x562BBCF20dF2cE73e7Cf8Ce7586Da9Ac4308b9A9'
  stateStorage: '0x85C8D065B35576852913e7b7D721E19E83834BF8'
  tournamentLogic: '0x126f67c1e2B100AF069B4EEd71455EFCbD8191BE'
